"""SQLAlchemy database model for team guidelines.

Team guidelines store summarized preferences learned from user feedback,
generated by batch LLM processing of raw feedback records.
"""

from datetime import UTC, datetime
from typing import TYPE_CHECKING
from uuid import uuid4

from sqlalchemy import DateTime, ForeignKey, Integer, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from api.models.base import Base

if TYPE_CHECKING:
    from api.models.organizations import Organization
    from api.models.repositories import Repository


class TeamGuidelines(Base):
    """Team guidelines summarized from user feedback.

    These guidelines are natural language text generated by an LLM
    that summarizes patterns from raw feedback signals. They are
    injected into code reviewer prompts to improve future reviews.
    """

    __tablename__ = "team_guidelines"
    __mapper_args__ = {"confirm_deleted_rows": False}

    # Primary key
    id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4, index=True, name="id"
    )

    # Ownership - organization required, repository optional (for org-wide guidelines)
    organization_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "organizations.id",
            ondelete="CASCADE",
            name="fk_team_guidelines_organization_id_organizations",
        ),
        index=True,
        name="organization_id",
    )
    repository_id: Mapped[UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "repositories.id",
            ondelete="CASCADE",
            name="fk_team_guidelines_repository_id_repositories",
        ),
        index=True,
        nullable=True,
        name="repository_id",
    )

    # Guidelines content
    guidelines_text: Mapped[str] = mapped_column(
        Text, nullable=False, name="guidelines_text"
    )  # Natural language guidelines from LLM

    # Metadata
    feedback_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, name="feedback_count"
    )  # How many feedbacks contributed

    # Timestamps
    last_updated: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
        name="last_updated",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC), name="created_at"
    )

    # Unique constraint on (organization_id, repository_id)
    __table_args__ = (
        UniqueConstraint(
            "organization_id",
            "repository_id",
            name="uq_team_guidelines_org_repo",
        ),
    )

    # Relationships
    organization: Mapped[Organization] = relationship("Organization")
    repository: Mapped[Repository | None] = relationship("Repository")

    def __repr__(self) -> str:
        """String representation."""
        scope = f"repo:{self.repository_id}" if self.repository_id else "org-wide"
        return f"<TeamGuidelines(id={self.id}, {scope}, feedback_count={self.feedback_count})>"
