// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AddGitLabSourceRequest
 *
 * Request schema for adding a GitLab source.
 */
export type AddGitLabSourceRequest = {
    /**
     * Access Token
     *
     * GitLab Personal Access Token (group or project level)
     */
    access_token: string;
    /**
     * Provider Url
     *
     * GitLab instance URL (default: https://gitlab.com)
     */
    provider_url?: string;
};

/**
 * AppConfig
 *
 * Application configuration exposed to frontend.
 */
export type AppConfig = {
    providers: ProviderConfig;
};

/**
 * DashboardStatsResponse
 *
 * Response schema for dashboard statistics.
 */
export type DashboardStatsResponse = {
    /**
     * Active Repos
     *
     * Repos with >= 1 completed review in last 7 days
     */
    active_repos: number;
    /**
     * Week-over-week change for active repos
     */
    active_repos_change: StatChange;
    /**
     * Avg Review Time Seconds
     *
     * Average review time in seconds (null if no data)
     */
    avg_review_time_seconds?: number | null;
    /**
     * Week-over-week change for avg review time
     */
    avg_review_time_change: StatChange;
    /**
     * Prs Reviewed
     *
     * Distinct PRs reviewed in last 7 days
     */
    prs_reviewed: number;
    /**
     * Week-over-week change for PRs reviewed
     */
    prs_reviewed_change: StatChange;
};

/**
 * DeleteLinkedRepositoryResponse
 *
 * Response schema for deleting a linked repository.
 */
export type DeleteLinkedRepositoryResponse = {
    /**
     * Message
     *
     * Success message
     */
    message: string;
    /**
     * Linked Repository Id
     *
     * ID of the deleted linked repository
     */
    linked_repository_id: string;
};

/**
 * DeleteOrganizationResponse
 *
 * Response for organization deletion.
 */
export type DeleteOrganizationResponse = {
    /**
     * Message
     *
     * Success message
     */
    message: string;
    /**
     * Organization Id
     *
     * Deleted organization ID (UUID)
     */
    organization_id: string;
};

/**
 * DeleteRepositoryResponse
 *
 * Response for repository deletion.
 */
export type DeleteRepositoryResponse = {
    /**
     * Message
     *
     * Success message
     */
    message: string;
    /**
     * Repository Id
     *
     * Deleted repository ID (UUID)
     */
    repository_id: string;
};

/**
 * DisconnectProviderResponse
 *
 * Response after disconnecting a provider.
 */
export type DisconnectProviderResponse = {
    /**
     * Message
     */
    message?: string;
    profile: UserProfile;
};

/**
 * GitHubAppInstallUrl
 *
 * GitHub App installation URL response.
 */
export type GitHubAppInstallUrl = {
    /**
     * Url
     */
    url: string;
    /**
     * App Name
     */
    app_name: string;
};

/**
 * GitLabSourceResponse
 *
 * Response schema for GitLab source creation.
 */
export type GitLabSourceResponse = {
    /**
     * Source Type
     *
     * Type of source: 'group' or 'project'
     */
    source_type: string;
    /**
     * Source Id
     *
     * ID of created Organization or Repository
     */
    source_id: string;
    /**
     * Source Name
     *
     * Name of the group or project
     */
    source_name: string;
    /**
     * Membership Created
     *
     * Whether membership was created for the user
     */
    membership_created: boolean;
    /**
     * Created At
     *
     * Timestamp of creation
     */
    created_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LinkedRepositoryCreate
 *
 * Request schema for creating a linked repository.
 */
export type LinkedRepositoryCreate = {
    /**
     * Url
     *
     * Full repository URL (e.g., 'https://github.com/owner/repo')
     */
    url: string;
    /**
     * Branch
     *
     * Branch name
     */
    branch: string;
};

/**
 * LinkedRepositoryResponse
 *
 * Response schema for a linked repository.
 */
export type LinkedRepositoryResponse = {
    /**
     * Id
     *
     * Linked repository ID (UUID)
     */
    id: string;
    /**
     * Linked Provider
     *
     * Provider type: 'github' or 'gitlab'
     */
    linked_provider: string;
    /**
     * Linked Provider Url
     *
     * Provider URL
     */
    linked_provider_url: string;
    /**
     * Linked Repo Path
     *
     * Repository path (e.g., 'owner/repo')
     */
    linked_repo_path: string;
    /**
     * Linked Branch
     *
     * Specific branch (null = default branch)
     */
    linked_branch: string | null;
    /**
     * Display Name
     *
     * Display name for UI
     */
    display_name: string | null;
    /**
     * Organization Id
     *
     * Organization ID if org-level link
     */
    organization_id: string | null;
    /**
     * Repository Id
     *
     * Repository ID if repo-level link
     */
    repository_id: string | null;
};

/**
 * ListGenericResponse[LinkedRepositoryResponse]
 */
export type ListGenericResponseLinkedRepositoryResponse = {
    /**
     * Objects
     */
    objects: Array<LinkedRepositoryResponse>;
    meta?: ListMetaResponse;
};

/**
 * ListGenericResponse[MemberListItem]
 */
export type ListGenericResponseMemberListItem = {
    /**
     * Objects
     */
    objects: Array<MemberListItem>;
    meta?: ListMetaResponse;
};

/**
 * ListGenericResponse[OrganizationListItem]
 */
export type ListGenericResponseOrganizationListItem = {
    /**
     * Objects
     */
    objects: Array<OrganizationListItem>;
    meta?: ListMetaResponse;
};

/**
 * ListGenericResponse[RepositoryListItem]
 */
export type ListGenericResponseRepositoryListItem = {
    /**
     * Objects
     */
    objects: Array<RepositoryListItem>;
    meta?: ListMetaResponse;
};

/**
 * ListMetaResponse
 *
 * Meta information for listing responses.
 */
export type ListMetaResponse = {
    /**
     * Timestamp of the request
     *
     * The timestamp when the request was made (Unix Time).
     */
    timestamp?: number;
};

/**
 * ListPaginatedResponse[PullRequestListItem]
 */
export type ListPaginatedResponsePullRequestListItem = {
    /**
     * Objects
     */
    objects: Array<PullRequestListItem>;
    meta?: ListMetaResponse;
    pagination: PaginationMeta;
};

/**
 * LogoutResponse
 *
 * Response for logout.
 */
export type LogoutResponse = {
    /**
     * Message
     *
     * Success message
     */
    message?: string;
};

/**
 * MemberListItem
 */
export type MemberListItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Provider Identity Id
     */
    provider_identity_id: string;
    /**
     * Username
     */
    username: string | null;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Role
     */
    role: string;
    /**
     * Reviewate Enabled
     */
    reviewate_enabled: boolean;
    /**
     * Is Linked
     *
     * Whether this identity is linked to a Reviewate user account
     */
    is_linked: boolean;
};

/**
 * MemberSettingsUpdate
 */
export type MemberSettingsUpdate = {
    /**
     * Reviewate Enabled
     */
    reviewate_enabled?: boolean | null;
};

/**
 * OAuthProvider
 *
 * OAuth provider types.
 */
export type OAuthProvider = 'google' | 'github' | 'gitlab';

/**
 * OrganizationListItem
 *
 * Organization item in list response (platform-agnostic).
 */
export type OrganizationListItem = {
    /**
     * Id
     *
     * Unique organization ID in our system
     */
    id: string;
    /**
     * Name
     *
     * Organization display name
     */
    name: string;
    /**
     * External Org Id
     *
     * External ID from GitHub/GitLab (org ID, group ID, project ID)
     */
    external_org_id: string;
    /**
     * Installation Id
     *
     * GitHub App installation ID, or GitLab token hash
     */
    installation_id?: string | null;
    /**
     * Provider
     *
     * Git provider type (github or gitlab)
     */
    provider: 'github' | 'gitlab';
    /**
     * Avatar Url
     *
     * Organization avatar URL from GitHub/GitLab
     */
    avatar_url?: string | null;
    /**
     * Created At
     *
     * When this organization was added to Reviewate
     */
    created_at: string;
    /**
     * Role
     *
     * Current user's role in this organization
     */
    role: 'admin' | 'member';
};

/**
 * OrganizationSettings
 */
export type OrganizationSettings = {
    /**
     * Automatic Review Trigger
     */
    automatic_review_trigger: string;
    /**
     * Automatic Summary Trigger
     */
    automatic_summary_trigger: string;
};

/**
 * OrganizationSettingsUpdate
 */
export type OrganizationSettingsUpdate = {
    automatic_review_trigger?: ApiRoutersOrganizationsSchemasAutomaticReviewTriggerEnum | null;
    automatic_summary_trigger?: ApiRoutersOrganizationsSchemasAutomaticReviewTriggerEnum | null;
};

/**
 * PaginationMeta
 *
 * Pagination metadata for list responses.
 */
export type PaginationMeta = {
    /**
     * Total
     *
     * Total number of items
     */
    total: number;
    /**
     * Limit
     *
     * Items per page
     */
    limit: number;
    /**
     * Page
     *
     * Current page number
     */
    page: number;
};

/**
 * ProviderConfig
 *
 * Configuration for available OAuth/integration providers.
 */
export type ProviderConfig = {
    /**
     * Github Enabled
     */
    github_enabled: boolean;
    /**
     * Gitlab Enabled
     */
    gitlab_enabled: boolean;
    /**
     * Google Enabled
     */
    google_enabled: boolean;
    /**
     * Gitlab Url
     */
    gitlab_url?: string | null;
};

/**
 * PullRequestDetail
 *
 * Detailed pull request information (base for list item).
 */
export type PullRequestDetail = {
    /**
     * Id
     *
     * Pull request ID (UUID)
     */
    id: string;
    /**
     * Organization Id
     *
     * Organization ID (UUID)
     */
    organization_id: string;
    /**
     * Repository Id
     *
     * Repository ID (UUID)
     */
    repository_id: string;
    /**
     * Pr Number
     *
     * Pull request number
     */
    pr_number: number;
    /**
     * External Pr Id
     *
     * External PR ID from provider
     */
    external_pr_id: string;
    /**
     * Title
     *
     * Pull request title
     */
    title: string;
    /**
     * Author
     *
     * Pull request author username
     */
    author: string;
    /**
     * State
     *
     * Pull request state (open, closed, merged)
     */
    state: string;
    /**
     * Head Branch
     *
     * Source branch
     */
    head_branch: string;
    /**
     * Base Branch
     *
     * Target branch
     */
    base_branch: string;
    /**
     * Head Sha
     *
     * Latest commit SHA on head branch
     */
    head_sha: string;
    /**
     * Pr Url
     *
     * Full URL to the pull request
     */
    pr_url: string;
    /**
     * Created At
     *
     * Creation timestamp
     */
    created_at: string;
    /**
     * Updated At
     *
     * Last update timestamp
     */
    updated_at: string;
    /**
     * Author Reviewate Disabled
     *
     * Whether the PR author has reviews disabled
     */
    author_reviewate_disabled?: boolean;
};

/**
 * PullRequestListItem
 *
 * Pull request item in list response, with latest execution info.
 */
export type PullRequestListItem = {
    /**
     * Id
     *
     * Pull request ID (UUID)
     */
    id: string;
    /**
     * Organization Id
     *
     * Organization ID (UUID)
     */
    organization_id: string;
    /**
     * Repository Id
     *
     * Repository ID (UUID)
     */
    repository_id: string;
    /**
     * Pr Number
     *
     * Pull request number
     */
    pr_number: number;
    /**
     * External Pr Id
     *
     * External PR ID from provider
     */
    external_pr_id: string;
    /**
     * Title
     *
     * Pull request title
     */
    title: string;
    /**
     * Author
     *
     * Pull request author username
     */
    author: string;
    /**
     * State
     *
     * Pull request state (open, closed, merged)
     */
    state: string;
    /**
     * Head Branch
     *
     * Source branch
     */
    head_branch: string;
    /**
     * Base Branch
     *
     * Target branch
     */
    base_branch: string;
    /**
     * Head Sha
     *
     * Latest commit SHA on head branch
     */
    head_sha: string;
    /**
     * Pr Url
     *
     * Full URL to the pull request
     */
    pr_url: string;
    /**
     * Created At
     *
     * Creation timestamp
     */
    created_at: string;
    /**
     * Updated At
     *
     * Last update timestamp
     */
    updated_at: string;
    /**
     * Author Reviewate Disabled
     *
     * Whether the PR author has reviews disabled
     */
    author_reviewate_disabled?: boolean;
    /**
     * Latest Execution Id
     *
     * Latest execution ID (UUID) or None
     */
    latest_execution_id?: string | null;
    /**
     * Latest Execution Status
     *
     * Latest execution status or None
     */
    latest_execution_status?: string | null;
    /**
     * Latest Execution Created At
     *
     * Latest execution creation time or None
     */
    latest_execution_created_at?: string | null;
    /**
     * Latest Execution Error Type
     *
     * Error type if latest execution failed
     */
    latest_execution_error_type?: string | null;
    /**
     * Latest Execution Error Detail
     *
     * Technical error detail if latest execution failed
     */
    latest_execution_error_detail?: string | null;
};

/**
 * RepositoryListItem
 *
 * Repository item in list response.
 */
export type RepositoryListItem = {
    /**
     * Id
     *
     * Repository ID (UUID)
     */
    id: string;
    /**
     * Organization Id
     *
     * Organization ID (UUID)
     */
    organization_id: string;
    /**
     * External Repo Id
     *
     * GitHub/GitLab repository ID
     */
    external_repo_id: string;
    /**
     * Provider
     *
     * Git platform (github or gitlab)
     */
    provider: string;
    /**
     * Name
     *
     * Repository name
     */
    name: string;
    /**
     * Web Url
     *
     * Full URL to the repository
     */
    web_url: string;
    /**
     * Avatar Url
     *
     * Repository avatar URL (owner's avatar)
     */
    avatar_url?: string | null;
    /**
     * Created At
     *
     * Creation timestamp
     */
    created_at: string;
};

/**
 * RepositorySettings
 *
 * Response schema for repository settings (raw values before inheritance).
 */
export type RepositorySettings = {
    /**
     * Automatic Review Trigger
     *
     * Trigger setting (null means inherits from organization)
     */
    automatic_review_trigger: string | null;
    /**
     * Automatic Summary Trigger
     *
     * Summary trigger (null means inherits from organization)
     */
    automatic_summary_trigger: string | null;
};

/**
 * RepositorySettingsUpdate
 *
 * Request schema for updating repository settings.
 *
 * Pass null to clear an override and inherit from organization.
 * Omit a field to leave it unchanged.
 */
export type RepositorySettingsUpdate = {
    /**
     * When to auto-trigger. Set to null to inherit from organization.
     */
    automatic_review_trigger?: ApiRoutersRepositoriesSchemasAutomaticReviewTriggerEnum | null;
    /**
     * When to auto-trigger summaries. Set to null to inherit from organization.
     */
    automatic_summary_trigger?: ApiRoutersRepositoriesSchemasAutomaticReviewTriggerEnum | null;
};

/**
 * StatChange
 *
 * Week-over-week change for a dashboard stat.
 */
export type StatChange = {
    /**
     * Percentage
     *
     * Percentage change (e.g. 5.0 for +5%)
     */
    percentage?: number | null;
    /**
     * Trend
     *
     * Trend direction
     */
    trend: 'up' | 'down' | 'neutral';
};

/**
 * TriggerReviewRequest
 *
 * Request schema for triggering a review.
 */
export type TriggerReviewRequest = {
    /**
     * Commit Sha
     *
     * Commit SHA to review
     */
    commit_sha: string;
};

/**
 * TriggerReviewResponse
 *
 * Response schema for triggered review.
 */
export type TriggerReviewResponse = {
    /**
     * Execution Id
     *
     * Execution ID (UUID)
     */
    execution_id: string;
    /**
     * Pull Request Id
     *
     * Pull request ID (UUID)
     */
    pull_request_id: string;
    /**
     * Status
     *
     * Execution status
     */
    status: string;
    /**
     * Commit Sha
     *
     * Commit SHA being reviewed
     */
    commit_sha: string;
    /**
     * Created At
     *
     * Execution creation timestamp
     */
    created_at: string;
};

/**
 * UninstallResponse
 *
 * Response for uninstall operation.
 */
export type UninstallResponse = {
    /**
     * Message
     *
     * Response message
     */
    message: string;
    /**
     * Success
     *
     * Whether the operation succeeded
     */
    success: boolean;
};

/**
 * UpdateProfileRequest
 *
 * Request schema for updating user profile.
 */
export type UpdateProfileRequest = {
    /**
     * Email
     *
     * New email address
     */
    email?: string | null;
    /**
     * Onboarding Step
     *
     * Current onboarding tour step
     */
    onboarding_step?: number | null;
};

/**
 * UpdateProfileResponse
 *
 * Response after updating profile.
 */
export type UpdateProfileResponse = {
    /**
     * Message
     */
    message?: string;
    profile: UserProfile;
};

/**
 * UserProfile
 *
 * User profile response.
 */
export type UserProfile = {
    /**
     * Id
     *
     * User ID (UUID)
     */
    id: string;
    /**
     * Email
     *
     * User email
     */
    email: string | null;
    /**
     * Created At
     *
     * Account creation timestamp
     */
    created_at: string;
    /**
     * Display Username
     *
     * Display username (first available)
     */
    display_username: string;
    /**
     * Onboarding Step
     *
     * Current onboarding tour step (None = not started)
     */
    onboarding_step?: number | null;
    /**
     * Github Username
     *
     * GitHub username (if linked)
     */
    github_username?: string | null;
    /**
     * Gitlab Username
     *
     * GitLab username (if linked)
     */
    gitlab_username?: string | null;
    /**
     * Github External Id
     *
     * GitHub user ID (if linked)
     */
    github_external_id?: string | null;
    /**
     * Gitlab External Id
     *
     * GitLab user ID (if linked)
     */
    gitlab_external_id?: string | null;
    /**
     * Google External Id
     *
     * Google user ID (if linked)
     */
    google_external_id?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WebhookResponse
 *
 * Generic webhook response.
 */
export type WebhookResponse = {
    /**
     * Message
     *
     * Response message
     */
    message: string;
    /**
     * Processed
     *
     * Whether the webhook was processed
     */
    processed?: boolean;
};

/**
 * AutomaticReviewTriggerEnum
 */
export type ApiRoutersOrganizationsSchemasAutomaticReviewTriggerEnum = 'creation' | 'commit' | 'label' | 'none';

/**
 * AutomaticReviewTriggerEnum
 *
 * Automatic review trigger options for API validation.
 */
export type ApiRoutersRepositoriesSchemasAutomaticReviewTriggerEnum = 'creation' | 'commit' | 'label' | 'none';

export type LoginGoogleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type LoginGithubData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/github';
};

export type LoginGitlabData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/gitlab';
};

export type OauthCallbackData = {
    body?: never;
    path: {
        provider: OAuthProvider;
    };
    query?: never;
    url: '/auth/callback/{provider}';
};

export type OauthCallbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthCallbackError = OauthCallbackErrors[keyof OauthCallbackErrors];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Successful Response
     */
    200: UserProfile;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateProfileData = {
    body: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type UpdateProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProfileError = UpdateProfileErrors[keyof UpdateProfileErrors];

export type UpdateProfileResponses = {
    /**
     * Successful Response
     */
    200: UpdateProfileResponse;
};

export type UpdateProfileResponse2 = UpdateProfileResponses[keyof UpdateProfileResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: LogoutResponse;
};

export type LogoutResponse2 = LogoutResponses[keyof LogoutResponses];

export type DisconnectProviderData = {
    body?: never;
    path: {
        provider: OAuthProvider;
    };
    query?: never;
    url: '/auth/providers/{provider}';
};

export type DisconnectProviderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DisconnectProviderError = DisconnectProviderErrors[keyof DisconnectProviderErrors];

export type DisconnectProviderResponses = {
    /**
     * Successful Response
     */
    200: DisconnectProviderResponse;
};

export type DisconnectProviderResponse2 = DisconnectProviderResponses[keyof DisconnectProviderResponses];

export type LinkProviderData = {
    body?: never;
    path: {
        provider: OAuthProvider;
    };
    query?: never;
    url: '/auth/link/{provider}';
};

export type LinkProviderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LinkProviderError = LinkProviderErrors[keyof LinkProviderErrors];

export type GetAppConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/config';
};

export type GetAppConfigResponses = {
    /**
     * Successful Response
     */
    200: AppConfig;
};

export type GetAppConfigResponse = GetAppConfigResponses[keyof GetAppConfigResponses];

export type ListOrganizationLinkedReposData = {
    body?: never;
    path: {
        /**
         * Org Id
         *
         * Organization ID (UUID)
         */
        org_id: string;
    };
    query?: never;
    url: '/organizations/{org_id}/linked-repos';
};

export type ListOrganizationLinkedReposErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOrganizationLinkedReposError = ListOrganizationLinkedReposErrors[keyof ListOrganizationLinkedReposErrors];

export type ListOrganizationLinkedReposResponses = {
    /**
     * Successful Response
     */
    200: ListGenericResponseLinkedRepositoryResponse;
};

export type ListOrganizationLinkedReposResponse = ListOrganizationLinkedReposResponses[keyof ListOrganizationLinkedReposResponses];

export type AddOrganizationLinkedRepoData = {
    body: LinkedRepositoryCreate;
    path: {
        /**
         * Org Id
         *
         * Organization ID (UUID)
         */
        org_id: string;
    };
    query?: never;
    url: '/organizations/{org_id}/linked-repos';
};

export type AddOrganizationLinkedRepoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddOrganizationLinkedRepoError = AddOrganizationLinkedRepoErrors[keyof AddOrganizationLinkedRepoErrors];

export type AddOrganizationLinkedRepoResponses = {
    /**
     * Successful Response
     */
    201: LinkedRepositoryResponse;
};

export type AddOrganizationLinkedRepoResponse = AddOrganizationLinkedRepoResponses[keyof AddOrganizationLinkedRepoResponses];

export type ListRepositoryLinkedReposData = {
    body?: never;
    path: {
        /**
         * Repo Id
         *
         * Repository ID (UUID)
         */
        repo_id: string;
    };
    query?: never;
    url: '/repositories/{repo_id}/linked-repos';
};

export type ListRepositoryLinkedReposErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRepositoryLinkedReposError = ListRepositoryLinkedReposErrors[keyof ListRepositoryLinkedReposErrors];

export type ListRepositoryLinkedReposResponses = {
    /**
     * Successful Response
     */
    200: ListGenericResponseLinkedRepositoryResponse;
};

export type ListRepositoryLinkedReposResponse = ListRepositoryLinkedReposResponses[keyof ListRepositoryLinkedReposResponses];

export type AddRepositoryLinkedRepoData = {
    body: LinkedRepositoryCreate;
    path: {
        /**
         * Repo Id
         *
         * Repository ID (UUID)
         */
        repo_id: string;
    };
    query?: never;
    url: '/repositories/{repo_id}/linked-repos';
};

export type AddRepositoryLinkedRepoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddRepositoryLinkedRepoError = AddRepositoryLinkedRepoErrors[keyof AddRepositoryLinkedRepoErrors];

export type AddRepositoryLinkedRepoResponses = {
    /**
     * Successful Response
     */
    201: LinkedRepositoryResponse;
};

export type AddRepositoryLinkedRepoResponse = AddRepositoryLinkedRepoResponses[keyof AddRepositoryLinkedRepoResponses];

export type DeleteLinkedRepoData = {
    body?: never;
    path: {
        /**
         * Linked Repo Id
         *
         * Linked repository ID (UUID)
         */
        linked_repo_id: string;
    };
    query?: never;
    url: '/linked-repos/{linked_repo_id}';
};

export type DeleteLinkedRepoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLinkedRepoError = DeleteLinkedRepoErrors[keyof DeleteLinkedRepoErrors];

export type DeleteLinkedRepoResponses = {
    /**
     * Successful Response
     */
    200: DeleteLinkedRepositoryResponse;
};

export type DeleteLinkedRepoResponse = DeleteLinkedRepoResponses[keyof DeleteLinkedRepoResponses];

export type ListOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/organizations';
};

export type ListOrganizationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOrganizationsError = ListOrganizationsErrors[keyof ListOrganizationsErrors];

export type ListOrganizationsResponses = {
    /**
     * Successful Response
     */
    200: ListGenericResponseOrganizationListItem;
};

export type ListOrganizationsResponse = ListOrganizationsResponses[keyof ListOrganizationsResponses];

export type StreamOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/organizations/stream';
};

export type StreamOrganizationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamOrganizationsError = StreamOrganizationsErrors[keyof StreamOrganizationsErrors];

export type StreamOrganizationsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetOrganizationSettingsData = {
    body?: never;
    path: {
        /**
         * Org Id
         *
         * Organization ID (UUID)
         */
        org_id: string;
    };
    query?: never;
    url: '/organizations/{org_id}/settings';
};

export type GetOrganizationSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrganizationSettingsError = GetOrganizationSettingsErrors[keyof GetOrganizationSettingsErrors];

export type GetOrganizationSettingsResponses = {
    /**
     * Successful Response
     */
    200: OrganizationSettings;
};

export type GetOrganizationSettingsResponse = GetOrganizationSettingsResponses[keyof GetOrganizationSettingsResponses];

export type UpdateOrganizationSettingsData = {
    body: OrganizationSettingsUpdate;
    path: {
        /**
         * Org Id
         *
         * Organization ID (UUID)
         */
        org_id: string;
    };
    query?: never;
    url: '/organizations/{org_id}/settings';
};

export type UpdateOrganizationSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOrganizationSettingsError = UpdateOrganizationSettingsErrors[keyof UpdateOrganizationSettingsErrors];

export type UpdateOrganizationSettingsResponses = {
    /**
     * Successful Response
     */
    200: OrganizationSettings;
};

export type UpdateOrganizationSettingsResponse = UpdateOrganizationSettingsResponses[keyof UpdateOrganizationSettingsResponses];

export type ListOrganizationMembersData = {
    body?: never;
    path: {
        /**
         * Org Id
         *
         * Organization ID (UUID)
         */
        org_id: string;
    };
    query?: never;
    url: '/organizations/{org_id}/members';
};

export type ListOrganizationMembersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOrganizationMembersError = ListOrganizationMembersErrors[keyof ListOrganizationMembersErrors];

export type ListOrganizationMembersResponses = {
    /**
     * Successful Response
     */
    200: ListGenericResponseMemberListItem;
};

export type ListOrganizationMembersResponse = ListOrganizationMembersResponses[keyof ListOrganizationMembersResponses];

export type GetOrganizationMemberData = {
    body?: never;
    path: {
        /**
         * Member Id
         *
         * Member ID (UUID)
         */
        member_id: string;
        /**
         * Org Id
         *
         * Organization ID (UUID)
         */
        org_id: string;
    };
    query?: never;
    url: '/organizations/{org_id}/members/{member_id}';
};

export type GetOrganizationMemberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrganizationMemberError = GetOrganizationMemberErrors[keyof GetOrganizationMemberErrors];

export type GetOrganizationMemberResponses = {
    /**
     * Successful Response
     */
    200: MemberListItem;
};

export type GetOrganizationMemberResponse = GetOrganizationMemberResponses[keyof GetOrganizationMemberResponses];

export type UpdateOrganizationMemberData = {
    body: MemberSettingsUpdate;
    path: {
        /**
         * Member Id
         *
         * Member ID (UUID)
         */
        member_id: string;
        /**
         * Org Id
         *
         * Organization ID (UUID)
         */
        org_id: string;
    };
    query?: never;
    url: '/organizations/{org_id}/members/{member_id}';
};

export type UpdateOrganizationMemberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOrganizationMemberError = UpdateOrganizationMemberErrors[keyof UpdateOrganizationMemberErrors];

export type UpdateOrganizationMemberResponses = {
    /**
     * Successful Response
     */
    200: MemberListItem;
};

export type UpdateOrganizationMemberResponse = UpdateOrganizationMemberResponses[keyof UpdateOrganizationMemberResponses];

export type ListRepositoriesData = {
    body?: never;
    path: {
        /**
         * Org Id
         *
         * Organization ID (UUID)
         */
        org_id: string;
    };
    query?: never;
    url: '/organizations/{org_id}/repositories';
};

export type ListRepositoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRepositoriesError = ListRepositoriesErrors[keyof ListRepositoriesErrors];

export type ListRepositoriesResponses = {
    /**
     * Successful Response
     */
    200: ListGenericResponseRepositoryListItem;
};

export type ListRepositoriesResponse = ListRepositoriesResponses[keyof ListRepositoriesResponses];

export type StreamRepositoriesData = {
    body?: never;
    path: {
        /**
         * Org Id
         *
         * Organization ID (UUID)
         */
        org_id: string;
    };
    query?: never;
    url: '/organizations/{org_id}/repositories/stream';
};

export type StreamRepositoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamRepositoriesError = StreamRepositoriesErrors[keyof StreamRepositoriesErrors];

export type StreamRepositoriesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteRepositoryData = {
    body?: never;
    path: {
        /**
         * Repo Id
         *
         * Repository ID (UUID)
         */
        repo_id: string;
    };
    query?: never;
    url: '/repositories/{repo_id}';
};

export type DeleteRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRepositoryError = DeleteRepositoryErrors[keyof DeleteRepositoryErrors];

export type DeleteRepositoryResponses = {
    /**
     * Successful Response
     */
    200: DeleteRepositoryResponse;
};

export type DeleteRepositoryResponse2 = DeleteRepositoryResponses[keyof DeleteRepositoryResponses];

export type ResetRepositorySettingsData = {
    body?: never;
    path: {
        /**
         * Repo Id
         *
         * Repository ID (UUID)
         */
        repo_id: string;
    };
    query?: never;
    url: '/repositories/{repo_id}/settings';
};

export type ResetRepositorySettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetRepositorySettingsError = ResetRepositorySettingsErrors[keyof ResetRepositorySettingsErrors];

export type ResetRepositorySettingsResponses = {
    /**
     * Successful Response
     */
    200: RepositorySettings;
};

export type ResetRepositorySettingsResponse = ResetRepositorySettingsResponses[keyof ResetRepositorySettingsResponses];

export type GetRepositorySettingsData = {
    body?: never;
    path: {
        /**
         * Repo Id
         *
         * Repository ID (UUID)
         */
        repo_id: string;
    };
    query?: never;
    url: '/repositories/{repo_id}/settings';
};

export type GetRepositorySettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRepositorySettingsError = GetRepositorySettingsErrors[keyof GetRepositorySettingsErrors];

export type GetRepositorySettingsResponses = {
    /**
     * Successful Response
     */
    200: RepositorySettings;
};

export type GetRepositorySettingsResponse = GetRepositorySettingsResponses[keyof GetRepositorySettingsResponses];

export type UpdateRepositorySettingsData = {
    body: RepositorySettingsUpdate;
    path: {
        /**
         * Repo Id
         *
         * Repository ID (UUID)
         */
        repo_id: string;
    };
    query?: never;
    url: '/repositories/{repo_id}/settings';
};

export type UpdateRepositorySettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRepositorySettingsError = UpdateRepositorySettingsErrors[keyof UpdateRepositorySettingsErrors];

export type UpdateRepositorySettingsResponses = {
    /**
     * Successful Response
     */
    200: RepositorySettings;
};

export type UpdateRepositorySettingsResponse = UpdateRepositorySettingsResponses[keyof UpdateRepositorySettingsResponses];

export type DashboardStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pull-requests/stream';
};

export type DashboardStreamErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DashboardStreamError = DashboardStreamErrors[keyof DashboardStreamErrors];

export type DashboardStreamResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListAllPullRequestsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Page
         */
        page?: number;
        /**
         * State
         */
        state?: string | null;
        /**
         * Created After
         */
        created_after?: string | null;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Repository Ids
         *
         * Filter by repository IDs
         */
        repository_ids?: Array<string> | null;
        /**
         * Author
         *
         * Filter by PR author username(s)
         */
        author?: Array<string> | null;
        /**
         * Organization Id
         *
         * Filter by organization ID
         */
        organization_id?: string | null;
    };
    url: '/pull-requests';
};

export type ListAllPullRequestsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAllPullRequestsError = ListAllPullRequestsErrors[keyof ListAllPullRequestsErrors];

export type ListAllPullRequestsResponses = {
    /**
     * Successful Response
     */
    200: ListPaginatedResponsePullRequestListItem;
};

export type ListAllPullRequestsResponse = ListAllPullRequestsResponses[keyof ListAllPullRequestsResponses];

export type GetDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pull-requests/stats';
};

export type GetDashboardStatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDashboardStatsError = GetDashboardStatsErrors[keyof GetDashboardStatsErrors];

export type GetDashboardStatsResponses = {
    /**
     * Successful Response
     */
    200: DashboardStatsResponse;
};

export type GetDashboardStatsResponse = GetDashboardStatsResponses[keyof GetDashboardStatsResponses];

export type ListPullRequestsData = {
    body?: never;
    path: {
        /**
         * Repo Id
         *
         * Repository ID (UUID)
         */
        repo_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Page
         */
        page?: number;
    };
    url: '/repositories/{repo_id}/pull-requests';
};

export type ListPullRequestsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPullRequestsError = ListPullRequestsErrors[keyof ListPullRequestsErrors];

export type ListPullRequestsResponses = {
    /**
     * Successful Response
     */
    200: ListPaginatedResponsePullRequestListItem;
};

export type ListPullRequestsResponse = ListPullRequestsResponses[keyof ListPullRequestsResponses];

export type GetPullRequestData = {
    body?: never;
    path: {
        /**
         * Pr Id
         *
         * Pull request ID (UUID)
         */
        pr_id: string;
    };
    query?: never;
    url: '/pull-requests/{pr_id}';
};

export type GetPullRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPullRequestError = GetPullRequestErrors[keyof GetPullRequestErrors];

export type GetPullRequestResponses = {
    /**
     * Successful Response
     */
    200: PullRequestDetail;
};

export type GetPullRequestResponse = GetPullRequestResponses[keyof GetPullRequestResponses];

export type TriggerReviewData = {
    body: TriggerReviewRequest;
    path: {
        /**
         * Pr Id
         *
         * Pull request ID (UUID)
         */
        pr_id: string;
    };
    query?: never;
    url: '/pull-requests/{pr_id}/review';
};

export type TriggerReviewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerReviewError = TriggerReviewErrors[keyof TriggerReviewErrors];

export type TriggerReviewResponses = {
    /**
     * Successful Response
     */
    202: TriggerReviewResponse;
};

export type TriggerReviewResponse2 = TriggerReviewResponses[keyof TriggerReviewResponses];

export type ListSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sources';
};

export type ListSourcesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSourcesError = ListSourcesErrors[keyof ListSourcesErrors];

export type ListSourcesResponses = {
    /**
     * Successful Response
     */
    200: ListGenericResponseOrganizationListItem;
};

export type ListSourcesResponse = ListSourcesResponses[keyof ListSourcesResponses];

export type GetGithubInstallUrlData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sources/github/install-url';
};

export type GetGithubInstallUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGithubInstallUrlError = GetGithubInstallUrlErrors[keyof GetGithubInstallUrlErrors];

export type GetGithubInstallUrlResponses = {
    /**
     * Successful Response
     */
    200: GitHubAppInstallUrl;
};

export type GetGithubInstallUrlResponse = GetGithubInstallUrlResponses[keyof GetGithubInstallUrlResponses];

export type UninstallGithubAppData = {
    body?: never;
    path: {
        /**
         * Org Id
         *
         * Organization ID (UUID)
         */
        org_id: string;
    };
    query?: never;
    url: '/sources/github/installations/{org_id}';
};

export type UninstallGithubAppErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UninstallGithubAppError = UninstallGithubAppErrors[keyof UninstallGithubAppErrors];

export type UninstallGithubAppResponses = {
    /**
     * Successful Response
     */
    200: UninstallResponse;
};

export type UninstallGithubAppResponse = UninstallGithubAppResponses[keyof UninstallGithubAppResponses];

export type AddGitlabSourceData = {
    body: AddGitLabSourceRequest;
    path?: never;
    query?: never;
    url: '/sources/gitlab';
};

export type AddGitlabSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddGitlabSourceError = AddGitlabSourceErrors[keyof AddGitlabSourceErrors];

export type AddGitlabSourceResponses = {
    /**
     * Successful Response
     */
    200: GitLabSourceResponse;
};

export type AddGitlabSourceResponse = AddGitlabSourceResponses[keyof AddGitlabSourceResponses];

export type DeleteGitlabOrganizationData = {
    body?: never;
    path: {
        /**
         * Org Id
         *
         * Organization ID (UUID)
         */
        org_id: string;
    };
    query?: never;
    url: '/sources/gitlab/organizations/{org_id}';
};

export type DeleteGitlabOrganizationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGitlabOrganizationError = DeleteGitlabOrganizationErrors[keyof DeleteGitlabOrganizationErrors];

export type DeleteGitlabOrganizationResponses = {
    /**
     * Successful Response
     */
    200: DeleteOrganizationResponse;
};

export type DeleteGitlabOrganizationResponse = DeleteGitlabOrganizationResponses[keyof DeleteGitlabOrganizationResponses];

export type GithubWebhookData = {
    body?: never;
    headers: {
        /**
         * X-Github-Event
         *
         * GitHub event type
         */
        'x-github-event': string;
        /**
         * X-Hub-Signature-256
         *
         * GitHub webhook signature
         */
        'x-hub-signature-256'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/webhooks/github';
};

export type GithubWebhookErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GithubWebhookError = GithubWebhookErrors[keyof GithubWebhookErrors];

export type GithubWebhookResponses = {
    /**
     * Successful Response
     */
    202: WebhookResponse;
};

export type GithubWebhookResponse = GithubWebhookResponses[keyof GithubWebhookResponses];

export type GitlabWebhookData = {
    body?: never;
    headers?: {
        /**
         * X-Gitlab-Token
         *
         * GitLab webhook secret token
         */
        'x-gitlab-token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/webhooks/gitlab';
};

export type GitlabWebhookErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GitlabWebhookError = GitlabWebhookErrors[keyof GitlabWebhookErrors];

export type GitlabWebhookResponses = {
    /**
     * Successful Response
     */
    202: WebhookResponse;
};

export type GitlabWebhookResponse = GitlabWebhookResponses[keyof GitlabWebhookResponses];
