"""Add unique constraint to repository external_repo_id

Revision ID: 4854079ed6bc
Revises: 3da13141aefc
Create Date: 2025-12-01 00:49:05.196550

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4854079ed6bc"
down_revision: Union[str, Sequence[str], None] = "3da13141aefc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repositories_external_repo_id"), table_name="repositories")
    op.create_index(
        op.f("ix_repositories_external_repo_id"), "repositories", ["external_repo_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repositories_external_repo_id"), table_name="repositories")
    op.create_index(
        op.f("ix_repositories_external_repo_id"), "repositories", ["external_repo_id"], unique=False
    )
    # ### end Alembic commands ###
