"""Database connection and session management."""

from api.database.base import Base, get_session
from api.database.execution import (
    db_create_execution,
    db_get_execution_by_id,
    db_get_latest_executions_for_pr,
    db_has_active_execution,
    db_update_execution_status,
)
from api.database.feedback import (
    db_create_feedback,
    db_delete_feedback,
    db_delete_feedback_by_organization,
    db_get_all_unprocessed_feedback_for_org,
    db_get_feedback_by_id,
    db_get_feedback_by_organization,
    db_get_unprocessed_feedback,
    db_mark_feedback_processed,
)
from api.database.identity import (
    db_get_identity_by_external_id,
    db_get_identity_by_id,
    db_get_or_create_provider_identity,
    db_get_user_identities,
    db_link_identities_to_user_by_external_id,
    db_link_identity_to_user,
    db_update_identity,
)
from api.database.linked_repository import (
    db_add_linked_repo,
    db_get_effective_linked_repos,
    db_get_linked_repo_by_id,
    db_get_org_linked_repos,
    db_get_repo_linked_repos,
    db_remove_linked_repo,
)
from api.database.organization import (
    db_create_organization,
    db_create_organization_membership,
    db_delete_organization,
    db_delete_organization_by_id,
    db_get_all_organizations,
    db_get_membership_by_username,
    db_get_organization_by_external_id,
    db_get_organization_by_id,
    db_get_organization_by_installation_id,
    db_get_organization_members,
    db_get_organization_membership,
    db_get_organization_membership_by_id,
    db_get_organization_memberships_by_identity,
    db_get_user_organization_ids,
    db_get_user_organizations_with_roles,
    db_sync_organization_membership,
    db_update_member_settings,
    db_update_organization_settings,
)
from api.database.pull_request import (
    db_create_pull_request,
    db_get_dashboard_stats,
    db_get_executions_for_pull_request,
    db_get_pull_request_by_id,
    db_get_pull_request_by_pr_number,
    db_get_pull_requests_by_repository,
    db_get_pull_requests_for_organizations,
    db_get_pull_requests_with_latest_execution,
    db_update_pull_request,
    db_upsert_pull_request,
)
from api.database.repository import (
    db_create_repository,
    db_create_repository_membership,
    db_delete_repository,
    db_delete_repository_by_id,
    db_get_repositories_by_organization,
    db_get_repository_by_external_id,
    db_get_repository_by_id,
    db_reset_repository_settings,
    db_sync_repository_membership,
    db_update_repository_settings,
)
from api.database.team_guidelines import (
    db_create_team_guidelines,
    db_delete_team_guidelines,
    db_delete_team_guidelines_by_scope,
    db_get_all_team_guidelines_for_org,
    db_get_effective_team_guidelines,
    db_get_team_guidelines,
    db_get_team_guidelines_by_id,
    db_update_team_guidelines,
    db_upsert_team_guidelines,
)
from api.database.user import (
    db_create_or_update_user,
    db_get_user_by_email,
    db_get_user_by_id,
)

__all__ = [
    "Base",
    "get_session",
    # Execution functions
    "db_create_execution",
    "db_get_execution_by_id",
    "db_get_latest_executions_for_pr",
    "db_has_active_execution",
    "db_update_execution_status",
    # Feedback functions
    "db_create_feedback",
    "db_delete_feedback",
    "db_delete_feedback_by_organization",
    "db_get_all_unprocessed_feedback_for_org",
    "db_get_feedback_by_id",
    "db_get_feedback_by_organization",
    "db_get_unprocessed_feedback",
    "db_mark_feedback_processed",
    # Identity functions
    "db_get_identity_by_external_id",
    "db_get_identity_by_id",
    "db_get_or_create_provider_identity",
    "db_get_user_identities",
    "db_link_identities_to_user_by_external_id",
    "db_link_identity_to_user",
    "db_update_identity",
    # Linked repository functions
    "db_add_linked_repo",
    "db_get_effective_linked_repos",
    "db_get_linked_repo_by_id",
    "db_get_org_linked_repos",
    "db_get_repo_linked_repos",
    "db_remove_linked_repo",
    # Team guidelines functions
    "db_create_team_guidelines",
    "db_delete_team_guidelines",
    "db_delete_team_guidelines_by_scope",
    "db_get_all_team_guidelines_for_org",
    "db_get_effective_team_guidelines",
    "db_get_team_guidelines",
    "db_get_team_guidelines_by_id",
    "db_update_team_guidelines",
    "db_upsert_team_guidelines",
    # Organization functions
    "db_create_organization",
    "db_create_organization_membership",
    "db_delete_organization",
    "db_delete_organization_by_id",
    "db_get_all_organizations",
    "db_get_membership_by_username",
    "db_get_organization_by_external_id",
    "db_get_organization_by_id",
    "db_get_organization_by_installation_id",
    "db_get_organization_members",
    "db_get_organization_membership",
    "db_get_organization_membership_by_id",
    "db_get_organization_memberships_by_identity",
    "db_get_user_organization_ids",
    "db_get_user_organizations_with_roles",
    "db_sync_organization_membership",
    "db_update_member_settings",
    "db_update_organization_settings",
    # Repository functions
    "db_create_repository",
    "db_create_repository_membership",
    "db_delete_repository",
    "db_delete_repository_by_id",
    "db_get_repositories_by_organization",
    "db_get_repository_by_external_id",
    "db_get_repository_by_id",
    "db_reset_repository_settings",
    "db_sync_repository_membership",
    "db_update_repository_settings",
    # Pull request functions
    "db_create_pull_request",
    "db_get_dashboard_stats",
    "db_get_executions_for_pull_request",
    "db_get_pull_request_by_id",
    "db_get_pull_request_by_pr_number",
    "db_get_pull_requests_by_repository",
    "db_get_pull_requests_for_organizations",
    "db_get_pull_requests_with_latest_execution",
    "db_update_pull_request",
    "db_upsert_pull_request",
    # User functions
    "db_create_or_update_user",
    "db_get_user_by_email",
    "db_get_user_by_id",
]
